### ISSUE TITLE
掲載終了日以外の変更(front)

### ISSUE THREAD

**Issue by ynakano1127** [tnct-spc/ibird#354]
# やること
* 右クリックのメニューの「掲載終了日の変更」から「掲示物の再設定」にする
* 掲載終了日の変更だけではなく
    * 優先する、しない
    * モバイル向けサイトでも表示
    * モバイル向けサイトでの表示名
も変えるようにする

# ブランチ名
`feature/Resetting`
# いじるファイル
`components/*`
# その他

**Comment by TYuto** [comment]
https://github.com/tnct-spc/ibird/pull/361
